x = ("costisBletsis")
#     0123456789012
print()
print("variable x =", x)
print()
print("length of variable x=", len(x))
print()
print("variable x isdigit:" , x.isdigit())
print()
print("variable x isalpha:" , x.isalpha())
print()
print("variable x islower:" , x.islower())
print()
print("variable x isupper:" , x.isupper())
print()
print("variable x lower:" , x.lower())
print()
print("variable x upper:" , x.upper())
print()
print("capitalize x: ", x.capitalize())
print()
print("strip(is) x: ", x.strip("is"))
print()
print("count(i) x: ", x.count("i"))
print()
print("find(c) x: ", x.find("c"))
print()
print("index(i) x: ", x.index("i",6))
print()
z = x.replace("i","H" ,2)
print("in variable x replace letter i with H 2 times: ",z)
print()
list = ["C", "o", "s", "t", "i", "s"]
list1 = [1,2,3,4,5,6]
print(list1)
name = "*".join(list)
print(name)
print()