name =len("Ilias")
print(name)
q = "12345".isdigit()
print(q)
w = "Ilias".isalpha()
print(w)
e = "Ilias".islower()
print(e)
r = "ILIAS".isupper()
print(r)
t = "ILIAS".lower()
print(t)
y = "Ilias".upper()
print(y)
u = "Ilias".capitalize()
print(u)
i = "Ilias".strip()
print(i)
o = "Ilias".count("Ilias")
print(o)
p = "".find("Ilias")
print(p)
a = "Ilias".replace("Ilias", "costis", )
print(a)
s = "Ilias".join(["1", "2", "3"])
print(s)
d = "Ilias".split("Ilias")
print(d)
